# --- Site settings ---
title: "Blog of the Statistics Course"
description: "Homeworks and projects for the Statistics course in Cybersecurity at La Sapienza University"
url: "https://fradb23.github.io"
baseurl: "/blog_statistics"

# --- Author info (string) ---
author: "Francesco Del Borgo"
author_email: "delborgo.2061739@studenti.uniroma1.it"
author_student_number: "2061739"

university: "Università La Sapienza di Roma"
course: "Cybersecurity"
academic_year: "2025/2026"

# --- Theme setup ---
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --- Appearance ---
navbar-col: "#004080"
navbar-text-col: "#ffffff"
navbar-border-col: "#003060"
footer-col: "#004080"
footer-text-col: "#ffffff"
page-col: "#ffffff"
link-col: "#0078d7"

# --- Navbar ---
navbar-links:
  Home: "/"
  Homeworks: "/articoli/"


# --- Markdown settings ---
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# --- Socials (optional) ---
social-network-links:
  email: "delborgo.2061739@studenti.uniroma1.it"
  github: "fradb23"
  linkedin: "francesco-del-borgo"

# --- Exclude unnecessary files ---
exclude:
  - "README.md"
  - "LICENSE"



# --- Collections ---
collections:
  articoli:
    output: true
    permalink: /articoli/:name/

